Реализация работы с датой/временем
e8tools/tool1cd pull request #102
Opened 2017-11-06 19:04 UTC by fishca

Первый набросок

2017-11-07 06:44 UTC, andreevlex commented on src/SystemClasses/System.cpp
> +	uint64_t ll = Int32x32To64(t, 10000000) + SEC_TO_UNIX_EPOCH;
тип безнаковый `uint64_t`, а используется `Int32x32To64` для знакового типа.

2017-11-07 13:32 UTC, fishca commented on src/SystemClasses/System.cpp
> +	uint64_t ll = Int32x32To64(t, 10000000) + SEC_TO_UNIX_EPOCH;
согласен, надо будет подправить

2017-11-07 19:24 UTC, dmpas requested changes
Неплохо! Поправить по мелочи.

2017-11-07 19:24 UTC, dmpas commented on src/ctool1cd/APIcfBase.h
> +
Зачем все эти инклуды в заголовке? Может, сразу в cpp перенести?

2017-11-07 19:24 UTC, dmpas commented on src/ctool1cd/APIcfBase.h
> +const int64_t EPOCH_START = 504911232000000;
Надо пояснить, что за эпох - одинэсный, виндовый, юниксовый.

2017-11-07 19:24 UTC, dmpas commented on src/ctool1cd/APIcfBase.cpp
> +	tmm.tm_year = 102;
Это что за значения??

2017-11-07 19:24 UTC, dmpas commented on src/SystemClasses/System.hpp
> +#define UInt32x32To64(a, b) ((uint64_t)(((uint64_t)((unsigned int)(a))) * ((unsigned int)(b))))
макросы - зло. Надо на функции переделать.

2017-11-07 19:24 UTC, dmpas commented on src/SystemClasses/System.cpp
> +	// TODO: реализовать кроссплатформенное преобразование из универсального (UTC) файлового времени в локальноое системное файловое время
Если работает, Тудуху надо убрать

2017-11-07 19:24 UTC, dmpas commented on src/SystemClasses/System.cpp
> +	// TODO: реализовать кроссплатформенное преобразование локального системного файлового времени в универсальное (UTC) файловое время
Тудуху убрать, если всё работает

2017-11-08 07:12 UTC, dmpas approved these changes
Внешне выглядит работоспособно.

2017-11-08 07:12 UTC, dmpas commented
По коду у меня придирок нет. Работает ли - покажут испытания.

2017-11-08 07:14 UTC, ava57r approved these changes

2017-11-08 07:27 UTC, merged