Реализована конвертация целого из шеснадцатиричного и обратно
e8tools/tool1cd pull request #149
Opened 2017-11-29 18:46 UTC by andreevlex

2017-11-29 18:50 UTC, andreevlex commented
тестов отрицательных целых не стал делать пока, почитаю.

2017-11-30 05:57 UTC, dmpas commented on src/tool1cd/APIcfBase.cpp
> +int32_t hex_to_int(std::array<char, HEX_INT_LEN>& hexstr)
а чего, аггау, а не стринг?

2017-11-30 06:04 UTC, dmpas commented
по-моему, шило на мыло поменяли.
Была одна `hex_to_int`, теперь две - `hex_to_int` и `get_int_of_index`, который ещё и замыкает на себя переменную, у которой вообще бы надо область видимости сократить, если по-хорошему.

2017-11-30 06:16 UTC, andreevlex commented on src/tool1cd/APIcfBase.cpp
> +int32_t hex_to_int(std::array<char, HEX_INT_LEN>& hexstr)
потому что std::string создается с буфером 16 байт, а тут 8 в два раза меньше.
std::array<char, 8>, потому что функция должна работать с 8 байтами, на кой ей еще размерность проверять? Усложняет сам метод.

2017-11-30 06:19 UTC, andreevlex commented
```c++
auto get_int_of_index = [&](uint32_t index) -> int32_t {
	std::array<char, HEX_INT_LEN> out;
	std::copy_n(temp_buf.begin() + index, out.size(), out.begin());
	return hex_to_int(out);
};
```
чем плоха эта лямбда?

2017-11-30 08:28 UTC, andreevlex commented
вот думаю можно точно переделать `int_to_hex` на примере `to_hex_string`.

2017-11-30 09:47 UTC, andreevlex commented
каков приговор?
1. убрать массив и заменить на стринг
2. переписать int_to_hex

2017-11-30 14:02 UTC, dmpas commented
Приговора пока нет. Допилка мне субъективно не люба, но объективно надо посмотреть, как было бы лучше и нагляднее.

2017-11-30 14:06 UTC, dmpas requested changes
Убрать широкой ноги лямбду.

2017-11-30 14:36 UTC, andreevlex commented
со стрингом интерфейс будет проще, переделаю. 
Надо будет контроль границ обрабатываемых данных добавить и ладно.
Лямбда не зашла и уберу ее прочь с глаз.

2017-12-01 05:50 UTC, dmpas approved these changes

2017-12-01 05:51 UTC, dmpas commented
Это уже более-менее хорошо выглядит. Мне только не нравится, что теперь копирование появилось. Ну да ладно, хватит это мусолить.

2017-12-01 05:51 UTC, merged