Feature/issue 90
e8tools/tool1cd pull request #159
Opened 2017-12-13 19:26 UTC by andreevlex

#90

2017-12-13 20:03 UTC, dmpas requested changes
Вынеси App из Main в отдельные файлы.

2017-12-13 20:05 UTC, dmpas commented
КоммандПарс заметно чище стал. Остальное неплохо, но на любителя.

2017-12-15 06:11 UTC, andreevlex commented
Я принципиально ничего не менял, только избавился от лапши параметров.
Какие предложения по дизайну?

2017-12-15 06:15 UTC, dmpas commented
> Какие предложения по дизайну?

только Апп вынести - это было бы логичным завершением. В остальном меня всё устраивает.

2017-12-15 06:55 UTC, dmpas approved these changes
Отлично!

2017-12-15 06:55 UTC, merged