Создан тип исключения PackDirectoryNotExistsException
e8tools/tool1cd pull request #169
Opened 2018-01-13 18:03 UTC by andreevlex

fix #165

2018-01-13 19:27 UTC, dmpas requested changes
Does not exist, емнип

2018-01-15 07:05 UTC, andreevlex commented
`PackDirectoryDoesNotExistException` да?

2018-01-15 07:17 UTC, dmpas commented
> PackDirectoryDoesNotExistException да?

ага

2018-01-15 07:24 UTC, andreevlex commented
java style =)

2018-01-15 08:59 UTC, dmpas approved these changes

2018-01-15 09:00 UTC, merged