Feature/issue 151
e8tools/tool1cd pull request #217
Opened 2018-02-24 15:46 UTC by andreevlex

2018-02-24 15:47 UTC, andreevlex commented
#151

2018-02-25 11:33 UTC, dmpas commented on src/tool1cd/cfapi/APIcfBase.cpp
> +	return BlockHeader;
Я в своё время не смог сообразить, может, ты скажешь, есть тут способ написать это же без сишных функций? или ну его?

2018-02-25 13:38 UTC, andreevlex commented on src/tool1cd/cfapi/APIcfBase.cpp
> +	return BlockHeader;
Я сделал так, вот думал это убрать как раз
```c++ 
std::string hex_prevempty = to_hex_string(prevempty, false);
 			std::copy(hex_prevempty.begin(),
 						hex_prevempty.end(),
						std::begin(block_header.next_page_addr_hex));
```

2018-02-26 05:49 UTC, dmpas commented on src/tool1cd/cfapi/APIcfBase.cpp
> +	return BlockHeader;
да, похоже на правду. можно даже тест на это сделать.

2018-02-26 07:58 UTC, dmpas requested changes
убрать сишный код. Остальное хорошо.

2018-02-26 18:56 UTC, dmpas approved these changes

2018-02-26 18:56 UTC, merged