Поддержка shapshots
e8tools/tool1cd pull request #71
Opened 2017-09-17 19:39 UTC by andreevlex

2017-09-18 06:25 UTC, dmpas commented
Отлично! Спасибо! Вечером посмотрю.

2017-09-18 06:37 UTC, andreevlex commented
#30

2017-09-18 09:02 UTC, andreevlex commented
тестировал на 5 версии без сэпшотов
на 6 версии со смешанными форматов снэпшотов
на 7 версии с снэпшотами с маркером `6fdfdf78-062a-46bb-8402-62145ae55764`

SNAPSHOTMAKER = `3721ca9e-a272-496b-a093-206ea7629574` - запакованный deflate'ом файл конфигурации
SNAPSHOTMAKER = `6fdfdf78-062a-46bb-8402-62145ae55764` - готовый файл конфигурации

2017-09-18 09:17 UTC, dmpas commented
хорошая работа!

2017-09-18 18:20 UTC, dmpas commented
Потестил. Есть пара моментов. Во-первых, стоит добавить в лог пометку о том, что берём снэпшот.

Во-вторых, какая-то жесть с производительностью. Снэпшоты сделаны для того, чтобы быстро взять готовую конфу, однако просто конфа у меня выгрузилась менее, чем за секунду, а версия, для которой есть снэпшот, выгружалась аж 20 секунд.

2017-09-18 18:31 UTC, dmpas commented
думаю, надо либо расчёт crc поменять - читать не побайтово, а блоками; либо TStream переделать на буферы; либо в TWrapperStream настроить размер буфера.

тут есть мысли на счёт последнего
https://stackoverflow.com/questions/5166263/how-to-get-iostream-to-perform-better

2017-09-18 19:42 UTC, dmpas requested changes
подправить расчёт crc32

2017-09-18 19:43 UTC, andreevlex commented
В Zlib есть расчет crc32
```c++
ZEXTERN uLong ZEXPORT crc32   OF((uLong crc, const Bytef *buf, uInt len));
/*
     Update a running CRC-32 with the bytes buf[0..len-1] and return the
   updated CRC-32.  If buf is Z_NULL, this function returns the required
   initial value for the crc.  Pre- and post-conditioning (one's complement) is
   performed within this function so it shouldn't be done by the application.
   Usage example:
     uLong crc = crc32(0L, Z_NULL, 0);
     while (read_buffer(buffer, length) != EOF) {
       crc = crc32(crc, buffer, length);
     }
     if (crc != original_crc) error();
*/
```

Можно его прикрутить.

2017-09-18 19:45 UTC, dmpas commented
тебе туда надо Bytef* передать, а перед этим - прочитать его. В то же чтение и упрёшься. Алгоритм-то нормальный, ввод-вывод надо подлатать.

2017-09-19 20:39 UTC, dmpas approved these changes

2017-09-19 20:39 UTC, merged